<?php
/**
 * @author emreuyguc <emreuyguc@gmail.com>
 * @copyright E.U.U 2022
 * @license Valid for 1 website (or project) and 1 domain only for each purchase of license
 * @package euu_customflag
 * @version 1.0.0
 *
 ** NOTICE OF LICENSE **
 *	This file is not open source ! Each license that you purchased is only available for 1 website (or project) and 1 domain only.
 *	If you want to use this file on more websites (or projects), you need to purchase additional licenses.
 * 	You are not allowed to redistribute, resell, lease, license, sub-license or offer our resources to any third party.
 *
 ** DISCLAIMER **
 *	This SOFTWARE PRODUCT is provided by the PROVIDER "as is" and "with all defects".
 *	The PROVIDER makes no representations or warranties regarding the safety, suitability, absence of viruses, inaccuracies,
typographical errors or other harmful components of this SOFTWARE PRODUCT.
 *	The use of any software has its own risks and you are solely responsible for determining whether this SOFTWARE PRODUCT is
compatible with your system and other software installed on it.
 *	In addition, you are solely responsible for maintaining your system and backing up your data, and the PROVIDER will not be liable for
any damage you may suffer in connection with use or modification.
 *
 **/

use euu_customflag\DbModels\GroupFlag;
use euu_customflag\DbModels\GroupProduct;

use euu_customflag\Helpers\DbModel;
use euu_customflag\Configs\ModuleConfigs;

if (!defined('_PS_VERSION_'))
	exit;

class FlagGroup extends DbModel {
	public $id;

	public $title;
	public $is_active;

	public $date_start;
	public $date_end;

	public $sql;

	#date
	public $date_add;
	public $date_upd;

	protected static $_USE_PREFIX = TRUE;
	public static $definition = [
		'table' => ModuleConfigs::NAME . '_flag_groups',
		'primary' => 'id_flag_group',
		'fields' => [
			'title' => [
				'type' => self::TYPE_STRING,
				'size' => 100,
				'required' => TRUE
			],
			'is_active' => [
				'type' => self::TYPE_BOOL,
				'required' => TRUE
			],
			'date_start' => [
				'type' => self::TYPE_DATE,
			],
			'date_end' => [
				'type' => self::TYPE_DATE,
			],
			'sql' => [
				'type' => self::TYPE_TEXT,
			],
			// NOTE : USE INSERT
			'date_add' => [
				'type' => self::TYPE_DATE,
			],
			'date_upd' => [
				'type' => self::TYPE_DATE,
			]
		],
	];

	public function delete(): bool {
		GroupFlag::deleteRow('id_flag_group = '.$this->id);
		GroupProduct::deleteRow('id_flag_group = '.$this->id);
		return parent::delete(); // TODO: Change the autogenerated stub
	}

}